# Generated by Django 4.0.2 on 2022-02-10 18:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='New Match!', max_length=50)),
                ('photo_one', models.URLField()),
                ('photo_two', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateField(auto_now=True)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'Nonbinary')], max_length=1)),
                ('preference', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'Nonbinary')], max_length=1)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, default=200)),
                ('location', models.CharField(max_length=50)),
                ('self_summary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='Nothing to see here!')),
                ('photo_url', models.URLField()),
                ('hidden', models.BooleanField(blank=True, default=False)),
                ('liked_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=200)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=200)),
                ('nerdy', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('musical', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('hard_working', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('romantic', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('album', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('conversation', models.ManyToManyField(related_name='conversations', to='vlyons.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reaction', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='vlyons.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='vlyons.user')),
            ],
        ),
    ]
