# Generated by Django 4.0.2 on 2022-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlyons', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, default='New Match!', max_length=50),
        ),
    ]
