# Generated by Django 4.0.2 on 2022-02-08 17:54

import accounts.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'Nonbinary')], max_length=1)),
                ('preference', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('N', 'Nonbinary')], max_length=1)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, default=200)),
                ('location', models.CharField(max_length=50)),
                ('self_summary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='Nothing to see here!')),
                ('photo_url', models.URLField()),
                ('hidden', models.BooleanField(blank=True, default=False)),
                ('liked_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=200)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=200)),
                ('nerdy', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('musical', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('hard_working', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('romantic', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('album', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
